services:
  react-vite-app:
    image: subul-fe:v1
    container_name: subul-fe
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - subul-network

networks:
  subul-network:
    driver: bridge
