name: Deploy to Server

on:
  push:
    branches:
      - main # Change to the branch you want to trigger deployment (e.g., main or master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 1221 -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts || true
        shell: bash

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p 1221 -i ~/.ssh/id_rsa deployer@${{ secrets.SERVER_IP }} << EOF
          cd /apps/subul-fe
          git pull origin main # Change 'main' to your branch name if needed
          docker-compose down
          docker-compose up -d --build
          EOF
        shell: bash